apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yz3kixfkd-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c175a581c0.04dg.p3.openshiftapps.com/rhtap/rhtap-qe:1fffa195f0de3df7063209f47ac96af057ee0d03@sha256:c90c7c391d3c1f08a652ded9db80e6dfd3b47c1df2d099f139a497489905fe2b
          name: container-image
